apiVersion: v1
kind: PersistentVolume
metadata:
    name: persistent-volume
spec:
    capacity:
       storage: 1Gi
    accessModes:
    -   ReadOnlyMany
    storageClassName: ""
    hostPath:
        path: "/mnt/static-web"