apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: persistent-volume-claim
spec:
    accessModes:
        -   ReadOnlyMany
    storageClassName: ""
    resources:
        requests:
            storage: 1Gi